--
-- PostgreSQL database dump
--

\restrict SRY6Dsdi7ObrDdyug0q8phtQ8wKJbj47reHykuoi3dQyYqAfpcbtw4yNNPueVnD

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-09-02 22:05:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16866)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    category_id integer NOT NULL,
    category_name character varying(255) NOT NULL,
    description text
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16865)
-- Name: categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16890)
-- Name: category_rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category_rules (
    category_rule_id integer NOT NULL,
    category_id integer NOT NULL,
    rule_id integer NOT NULL
);


ALTER TABLE public.category_rules OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16889)
-- Name: category_rules_category_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category_rules ALTER COLUMN category_rule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_rules_category_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16944)
-- Name: compliance_results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.compliance_results (
    result_id integer NOT NULL,
    scan_id integer NOT NULL,
    overall_status character varying(30) NOT NULL,
    total_rules integer DEFAULT 0,
    passed_rules integer DEFAULT 0,
    failed_rules integer DEFAULT 0,
    checked_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.compliance_results OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16943)
-- Name: compliance_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.compliance_results ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compliance_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16964)
-- Name: compliance_rule_results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.compliance_rule_results (
    rule_result_id integer NOT NULL,
    result_id integer NOT NULL,
    rule_id integer NOT NULL,
    status character varying(20) NOT NULL,
    extracted_value text,
    expected_value text,
    remarks text
);


ALTER TABLE public.compliance_rule_results OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16963)
-- Name: compliance_rule_results_rule_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.compliance_rule_results ALTER COLUMN rule_result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compliance_rule_results_rule_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16911)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    product_id integer NOT NULL,
    category_id integer NOT NULL,
    product_name character varying(255) NOT NULL,
    manufacturer_name character varying(255),
    brand_name character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16910)
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16876)
-- Name: rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rules (
    rule_id integer NOT NULL,
    rule_code character varying(50) NOT NULL,
    rule_reference character varying(255),
    rule_title character varying(255) NOT NULL,
    description text,
    applicability text,
    rule_config jsonb,
    active boolean DEFAULT true
);


ALTER TABLE public.rules OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16875)
-- Name: rules_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rules ALTER COLUMN rule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rules_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16928)
-- Name: scans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.scans (
    scan_id integer NOT NULL,
    product_id integer NOT NULL,
    image_path character varying(500),
    scanned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ocr_text text
);


ALTER TABLE public.scans OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16927)
-- Name: scans_scan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.scans ALTER COLUMN scan_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scans_scan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5068 (class 0 OID 16866)
-- Dependencies: 220
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (category_id, category_name, description) FROM stdin;
1	Pharma	Pharmaceutical and medicinal products
2	Cosmetics	Cosmetic and personal care products
3	Packaged Items	Packaged commodities and consumer goods
4	Household	Household and domestic-use products
5	Stationery	Stationery and writing products
6	Electronics	Electronic and electrical consumer products
\.


--
-- TOC entry 5072 (class 0 OID 16890)
-- Dependencies: 224
-- Data for Name: category_rules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category_rules (category_rule_id, category_id, rule_id) FROM stdin;
1	1	1
2	1	2
3	1	3
4	1	4
5	2	1
6	2	2
7	2	3
8	2	4
9	3	1
10	3	2
11	3	3
12	3	4
13	4	1
14	4	2
15	4	3
16	4	4
17	5	1
18	5	2
19	5	3
20	5	4
21	6	1
22	6	2
23	6	3
24	6	4
\.


--
-- TOC entry 5078 (class 0 OID 16944)
-- Dependencies: 230
-- Data for Name: compliance_results; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.compliance_results (result_id, scan_id, overall_status, total_rules, passed_rules, failed_rules, checked_at) FROM stdin;
\.


--
-- TOC entry 5080 (class 0 OID 16964)
-- Dependencies: 232
-- Data for Name: compliance_rule_results; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.compliance_rule_results (rule_result_id, result_id, rule_id, status, extracted_value, expected_value, remarks) FROM stdin;
\.


--
-- TOC entry 5074 (class 0 OID 16911)
-- Dependencies: 226
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (product_id, category_id, product_name, manufacturer_name, brand_name, created_at) FROM stdin;
\.


--
-- TOC entry 5070 (class 0 OID 16876)
-- Dependencies: 222
-- Data for Name: rules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rules (rule_id, rule_code, rule_reference, rule_title, description, applicability, rule_config, active) FROM stdin;
1	LMPC-001	Rule 6(1)(a)	Manufacturer / Packer / Importer Name & Address	The package should declare the name and address of the manufacturer, packer or importer, as applicable.	Applicable to packaged commodities subject to the Legal Metrology (Packaged Commodities) Rules.	{"type": "text", "required": true}	t
2	LMPC-002	Rule 6(1)(b)	Common / Generic Name of Commodity	The package should declare the common or generic name of the commodity.	Applicable to packaged commodities subject to the Legal Metrology (Packaged Commodities) Rules.	{"type": "text", "required": true}	t
3	LMPC-003	Rule 6(1)(c)	Net Quantity	The package should declare the net quantity of the commodity in the prescribed standard unit.	Applicable to packaged commodities subject to the Legal Metrology (Packaged Commodities) Rules.	{"type": "quantity", "required": true}	t
4	LMPC-004	Rule 6(1)(d)	Month & Year of Manufacture / Pre-packing / Import	The package should declare the month and year of manufacture, pre-packing or import, as applicable.	Applicable to packaged commodities subject to the Legal Metrology (Packaged Commodities) Rules.	{"type": "date", "required": true}	t
\.


--
-- TOC entry 5076 (class 0 OID 16928)
-- Dependencies: 228
-- Data for Name: scans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.scans (scan_id, product_id, image_path, scanned_at, ocr_text) FROM stdin;
\.


--
-- TOC entry 5086 (class 0 OID 0)
-- Dependencies: 219
-- Name: categories_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_category_id_seq', 6, true);


--
-- TOC entry 5087 (class 0 OID 0)
-- Dependencies: 223
-- Name: category_rules_category_rule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_rules_category_rule_id_seq', 24, true);


--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 229
-- Name: compliance_results_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.compliance_results_result_id_seq', 1, true);


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 231
-- Name: compliance_rule_results_rule_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.compliance_rule_results_rule_result_id_seq', 4, true);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 225
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_product_id_seq', 1, true);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 221
-- Name: rules_rule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rules_rule_id_seq', 4, true);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 227
-- Name: scans_scan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.scans_scan_id_seq', 1, true);


--
-- TOC entry 4894 (class 2606 OID 16874)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (category_id);


--
-- TOC entry 4900 (class 2606 OID 16897)
-- Name: category_rules category_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_rules
    ADD CONSTRAINT category_rules_pkey PRIMARY KEY (category_rule_id);


--
-- TOC entry 4908 (class 2606 OID 16955)
-- Name: compliance_results compliance_results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_results
    ADD CONSTRAINT compliance_results_pkey PRIMARY KEY (result_id);


--
-- TOC entry 4910 (class 2606 OID 16957)
-- Name: compliance_results compliance_results_scan_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_results
    ADD CONSTRAINT compliance_results_scan_id_key UNIQUE (scan_id);


--
-- TOC entry 4912 (class 2606 OID 16974)
-- Name: compliance_rule_results compliance_rule_results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_rule_results
    ADD CONSTRAINT compliance_rule_results_pkey PRIMARY KEY (rule_result_id);


--
-- TOC entry 4904 (class 2606 OID 16921)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);


--
-- TOC entry 4896 (class 2606 OID 16886)
-- Name: rules rules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rules
    ADD CONSTRAINT rules_pkey PRIMARY KEY (rule_id);


--
-- TOC entry 4898 (class 2606 OID 16888)
-- Name: rules rules_rule_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rules
    ADD CONSTRAINT rules_rule_code_key UNIQUE (rule_code);


--
-- TOC entry 4906 (class 2606 OID 16937)
-- Name: scans scans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scans
    ADD CONSTRAINT scans_pkey PRIMARY KEY (scan_id);


--
-- TOC entry 4902 (class 2606 OID 16899)
-- Name: category_rules uq_category_rule; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_rules
    ADD CONSTRAINT uq_category_rule UNIQUE (category_id, rule_id);


--
-- TOC entry 4913 (class 2606 OID 16900)
-- Name: category_rules fk_category_rules_category; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_rules
    ADD CONSTRAINT fk_category_rules_category FOREIGN KEY (category_id) REFERENCES public.categories(category_id);


--
-- TOC entry 4914 (class 2606 OID 16905)
-- Name: category_rules fk_category_rules_rule; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_rules
    ADD CONSTRAINT fk_category_rules_rule FOREIGN KEY (rule_id) REFERENCES public.rules(rule_id);


--
-- TOC entry 4917 (class 2606 OID 16958)
-- Name: compliance_results fk_compliance_results_scan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_results
    ADD CONSTRAINT fk_compliance_results_scan FOREIGN KEY (scan_id) REFERENCES public.scans(scan_id);


--
-- TOC entry 4915 (class 2606 OID 16922)
-- Name: products fk_products_category; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES public.categories(category_id);


--
-- TOC entry 4918 (class 2606 OID 16975)
-- Name: compliance_rule_results fk_rule_results_result; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_rule_results
    ADD CONSTRAINT fk_rule_results_result FOREIGN KEY (result_id) REFERENCES public.compliance_results(result_id);


--
-- TOC entry 4919 (class 2606 OID 16980)
-- Name: compliance_rule_results fk_rule_results_rule; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compliance_rule_results
    ADD CONSTRAINT fk_rule_results_rule FOREIGN KEY (rule_id) REFERENCES public.rules(rule_id);


--
-- TOC entry 4916 (class 2606 OID 16938)
-- Name: scans fk_scans_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.scans
    ADD CONSTRAINT fk_scans_product FOREIGN KEY (product_id) REFERENCES public.products(product_id);


-- Completed on 2026-09-02 22:05:58

--
-- PostgreSQL database dump complete
--

\unrestrict SRY6Dsdi7ObrDdyug0q8phtQ8wKJbj47reHykuoi3dQyYqAfpcbtw4yNNPueVnD

